In [2]:
import numpy as np
print("Numpy version :",np.__version__)

Numpy version : 2.5.3


Arrays

In [3]:
# create 1d array
x=np.array([10,20,30,40])
print("1d array",x)
x=np.array([[1,2,3],[4,5,6]])
print("2d array : ",x)
tensor=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,3,4]]])
print(f"Tensor : {tensor}")

1d array [10 20 30 40]
2d array :  [[1 2 3]
 [4 5 6]]
Tensor : [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 3 4]]]


Array properties

In [4]:
print("Shape :",x.shape)  # Rows and columns
print ("Dimension :",x.ndim)
print("Type :",x.dtype)
print("size :",x.size)


Shape : (2, 3)
Dimension : 2
Type : int64
size : 6


Creating Common arrays

In [5]:
print("Zroes :\n",np.zeros((3,4)))
print("ones :\n",np.ones((2,4)))
print("identity :\n",np.eye((4)))
print("Range :\n",np.arange(0,20,4))
print("Linspace:\n",np.linspace(0,10,15))

Zroes :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
identity :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Range :
 [ 0  4  8 12 16]
Linspace:
 [ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


index and slicing


In [6]:
x=np.array([10,20,30,40,50])
print("First:",x[0])
print("last:",x[-1])
print("Second last",x[2])
print("First three:",x[:3])
print("every second :",x[::2])
print("Reverse :",x[::-1])

# 2D indexing: [row, column]
y=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print("2d array : \n",y)
print("First:",y[0,0])
print("second row:",y[1,:])
print("Second last",y[2])
print("Third column:",y[:,2])
print("every second :",y[::2])
print("Reverse :",y[::-1])

First: 10
last: 50
Second last 30
First three: [10 20 30]
every second : [10 30 50]
Reverse : [50 40 30 20 10]
2d array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First: 1
second row: [4 5 6]
Second last [7 8 9]
Third column: [3 6 9]
every second : [[1 2 3]
 [7 8 9]]
Reverse : [[7 8 9]
 [4 5 6]
 [1 2 3]]


Boolean filtering

In [7]:
print("Greater than 20",x[x>20])
print("Greater than 25 and less than 60",x[(x >= 25) & (x <= 60)])

Greater than 20 [30 40 50]
Greater than 25 and less than 60 [30 40 50]


## 6. Vectorized Arithmetic


In [8]:
x = np.array([1,2,3,4])
print('x + 10:', x + 10)
print('x * 2:', x * 2)
print('x squared:', x ** 2)
print('x / 2:', x / 2)

a = np.array([1,2,3])
b = np.array([10,20,30])
print('Element-wise addition:', a + b)
print('Element-wise multiplication:', a * b)

x + 10: [11 12 13 14]
x * 2: [2 4 6 8]
x squared: [ 1  4  9 16]
x / 2: [0.5 1.  1.5 2. ]
Element-wise addition: [11 22 33]
Element-wise multiplication: [10 40 90]


## 7. Broadcasting

Broadcasting lets NumPy combine arrays of compatible shapes. This is common when adding biases in ML/DL.

In [9]:
x=np.array([[1,3,4],[5,6,7]])
print("add scalar :\n",x+10)

row_values = np.array([10,20,30])
print('Row-wise broadcasting:\n', x + row_values)

add scalar :
 [[11 13 14]
 [15 16 17]]
Row-wise broadcasting:
 [[11 23 34]
 [15 26 37]]


## 8. Mathematical Functions

In [10]:
x = np.array([1,4,9,16], dtype=float)
print("square root",np.sqrt(x))
print("exponent",np.exp(x))
print("log",np.log(x))
print('abs:', np.abs(np.array([-5,2,-8])))

square root [1. 2. 3. 4.]
exponent [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
log [0.         1.38629436 2.19722458 2.77258872]
abs: [5 2 8]


## 9. Statistics


In [11]:
x = np.array([10,20,30,40,50])
print('Sum:', np.sum(x))

print("mean",np.mean(x))
print("Median",np.median(x))
print("satndard deviation",np.std(x))
print("min",np.min(x))
print("max",np.max(x))
print("Variance",np.var(x))
print("25th percentile",np.percentile(x,25))
print("75th percentile",np.percentile(x,75))

Sum: 150
mean 30.0
Median 30.0
satndard deviation 14.142135623730951
min 10
max 50
Variance 200.0
25th percentile 20.0
75th percentile 40.0


## 12. Normalization and Standardization

Min-Max: `(x - min) / (max - min)`

Z-score: `(x - mean) / std`

In [12]:
x = np.array([10,20,30,40,50], dtype=float)
minmax=(x-np.min(x)/np.max(x)-np.min(x))
z=(x-np.mean(x))/np.std(x)
print("Minmax :",minmax)
print("z score : ",z)
print("new mean ",np.mean(z))
print("new std :",np.std(z))


Minmax : [-0.2  9.8 19.8 29.8 39.8]
z score :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
new mean  0.0
new std : 0.9999999999999999


## 13. Linear Algebra: Vectors and Matrices

These operations are fundamental to linear regression, neural networks, embeddings, and deep learning layers.

In [13]:
v = np.array([2,3,4])
print("vector norm",np.linalg.norm(v))

a=np.array([1,2,3])
b=np.array([4,5,6])
print("Dot product",np.dot(a,b))
print("Dor product using @",a@b)

A=np.array([[1,2],[4,5]])
B=np.array([[6,7],[8,9]])
print("Element wise",A*B)
print("Matrix Multiplication",A@B)

vector norm 5.385164807134504
Dot product 32
Dor product using @ 32
Element wise [[ 6 14]
 [32 45]]
Matrix Multiplication [[22 25]
 [64 73]]


## 16. ML Prediction: `y_hat = Xw + b`

In [16]:
# One feature
X = np.array([1,2,3,4], dtype=float)
w = 10.0
b = 5.0
y_pred = X*w + b
print('Predictions:', y_pred)

# Multiple features
X = np.array([[1,2],[2,3],[3,4],[4,5]], dtype=float)
w = np.array([10,20], dtype=float)
b = 5.0
print('Multiple-feature predictions:', X @ w + b)

Predictions: [15. 25. 35. 45.]
Multiple-feature predictions: [ 55.  85. 115. 145.]


## 17. Loss Functions

MSE: `mean((actual - predicted)^2)`

MAE: `mean(abs(actual - predicted))`

In [18]:
y_actual = np.array([10,20,30,40], dtype=float)
y_pred = np.array([12,18,33,37], dtype=float)
errors=y_actual-y_pred
squared_errors=errors**2
mse=np.mean(squared_errors)
mae=np.mean(np.abs(errors))
print('Errors:', errors)
print('Squared errors:', squared_errors)
print('MSE:', mse)
print('MAE:', mae)

Errors: [-2.  2. -3.  3.]
Squared errors: [4. 4. 9. 9.]
MSE: 6.5
MAE: 2.5


## 18. Activation Functions

In [21]:
x = np.array([-2,-1,0,1,2], dtype=float)

def sigmoid(x):
    return 1/(1+np.exp(-x))
def Relu(x):
    return np.maximum(0,x)
print ('Sigmoid :',sigmoid(x))
print('ReLu',Relu(x))
print("tanh ",np.tanh(x))

Sigmoid : [0.11920292 0.26894142 0.5        0.73105858 0.88079708]
ReLu [0. 0. 0. 1. 2.]
tanh  [-0.96402758 -0.76159416  0.          0.76159416  0.96402758]


## 19. Softmax

Softmax converts class scores into probabilities whose sum is 1. Subtracting the maximum score improves numerical stability.

In [22]:
def softmax(x):
    exp_x=np.exp(x-np.max(x))
    return exp_x/np.sum(exp_x)
scores = np.array([2.0,1.0,0.1])
probabilities = softmax(scores)
print('Probabilities:', probabilities)
print('Sum:', np.sum(probabilities))

Probabilities: [0.65900114 0.24243297 0.09856589]
Sum: 1.0


## 21. Random Numbers and Reproducibility

In [33]:
rng=np.random.default_rng(42)
print("Rabdom Floats",rng.random(5))
print("Random intergers",rng.integers(0,10,size=(2,3)))

samples=rng.normal(loc=0,scale=1,size=1000)
print('Normal sample mean:', np.mean(samples))
print('Normal sample std:', np.std(samples))

Rabdom Floats [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Random intergers [[5 9 7]
 [7 7 7]]
Normal sample mean: -0.026336374220094834
Normal sample std: 0.9855386652418566


## 22. Neural-Network Weight Initialization

In [36]:
rng=np.random.default_rng(42)
weights=rng.normal(0,0.01,size=(3,4))
bias=np.zeros(4)
print("Weight shape ",weights.shape)
print("Weights",weights)
print("Bias",bias)


Weight shape  (3, 4)
Weights [[ 0.00304717 -0.01039984  0.00750451  0.00940565]
 [-0.01951035 -0.0130218   0.0012784  -0.00316243]
 [-0.00016801 -0.00853044  0.00879398  0.00777792]]
Bias [0. 0. 0. 0.]


## 23. Shuffle and Simple Train/Test Split

In [39]:
rng=np.random.default_rng(42)
X=np.arange(20).reshape(10,2)
y=np.arange(10)

indices=rng.permutation(len(X))
train_size=int(0.8*10)
train_idx=indices[:train_size]
test_idx=indices[train_size:]
X_train,X_test=X[train_idx],X[test_idx]
y_train,y_test=y[train_idx],y[train_size]
print('X_train shape:', X_train.shape)  # Output: (8, 2)  -> 8 samples, 2 features
print('X_test shape:', X_test.shape)  
print('X_train :',X_train)  # Output: (2, 2)  -> 2 samples, 2 features
print('y_train:', y_train)              # 8 training labels
print('y_test:', y_test)                # 2 testing labels


X_train shape: (8, 2)
X_test shape: (2, 2)
X_train : [[10 11]
 [12 13]
 [ 0  1]
 [14 15]
 [ 6  7]
 [ 4  5]
 [ 8  9]
 [18 19]]
y_train: [5 6 0 7 3 2 4 9]
y_test: 8


## 25. Missing Values and Cleaning

In [43]:
x = np.array([10,20,np.nan,40,50])
print("NAN",np.isnan(x))
print("Sum nan",np.sum(np.isnan(x)))
print("Mean ignoring NAN ",np.nanmean(x))

x_clean=np.nan_to_num(x,nan=np.nanmean(x))
print("CLeaned",x_clean)

NAN [False False  True False False]
Sum nan 1
Mean ignoring NAN  30.0
CLeaned [10. 20. 30. 40. 50.]


## 26. Unique Values and Counts