In [48]:
import numpy as np
print("Numpy version :",np.__version__)

Numpy version : 2.5.3


Arrays

In [49]:
# create 1d array
x=np.array([10,20,30,40])
print("1d array",x)
x=np.array([[1,2,3],[4,5,6]])
print("2d array : ",x)
tensor=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,3,4]]])
print(f"Tensor : {tensor}")

1d array [10 20 30 40]
2d array :  [[1 2 3]
 [4 5 6]]
Tensor : [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 3 4]]]


Array properties

In [50]:
print("Shape :",x.shape)  # Rows and columns
print ("Dimension :",x.ndim)
print("Type :",x.dtype)
print("size :",x.size)


Shape : (2, 3)
Dimension : 2
Type : int64
size : 6


Creating Common arrays

In [51]:
print("Zroes :\n",np.zeros((3,4)))
print("ones :\n",np.ones((2,4)))
print("identity :\n",np.eye((4)))
print("Range :\n",np.arange(0,20,4))
print("Linspace:\n",np.linspace(0,10,15))

Zroes :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
identity :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Range :
 [ 0  4  8 12 16]
Linspace:
 [ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


index and slicing


In [52]:
x=np.array([10,20,30,40,50])
print("First:",x[0])
print("last:",x[-1])
print("Second last",x[2])
print("First three:",x[:3])
print("every second :",x[::2])
print("Reverse :",x[::-1])

# 2D indexing: [row, column]
y=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print("2d array : \n",y)
print("First:",y[0,0])
print("second row:",y[1,:])
print("Second last",y[2])
print("Third column:",y[:,2])
print("every second :",y[::2])
print("Reverse :",y[::-1])

First: 10
last: 50
Second last 30
First three: [10 20 30]
every second : [10 30 50]
Reverse : [50 40 30 20 10]
2d array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First: 1
second row: [4 5 6]
Second last [7 8 9]
Third column: [3 6 9]
every second : [[1 2 3]
 [7 8 9]]
Reverse : [[7 8 9]
 [4 5 6]
 [1 2 3]]


Boolean filtering

In [ ]:
print("Greater than 20",x[x>20])
print("Greater than 25 and less than 60",x[(x >= 25) & (x <= 60)])

Greater than 20 [30 40 50]
Greater than 20 and less than 50 [30 40 50]


## 6. Vectorized Arithmetic


In [56]:
x = np.array([1,2,3,4])
print('x + 10:', x + 10)
print('x * 2:', x * 2)
print('x squared:', x ** 2)
print('x / 2:', x / 2)

a = np.array([1,2,3])
b = np.array([10,20,30])
print('Element-wise addition:', a + b)
print('Element-wise multiplication:', a * b)

x + 10: [11 12 13 14]
x * 2: [2 4 6 8]
x squared: [ 1  4  9 16]
x / 2: [0.5 1.  1.5 2. ]
Element-wise addition: [11 22 33]
Element-wise multiplication: [10 40 90]


## 7. Broadcasting

Broadcasting lets NumPy combine arrays of compatible shapes. This is common when adding biases in ML/DL.

In [60]:
x=np.array([[1,3,4],[5,6,7]])
print("add scalar :\n",x+10)

row_values = np.array([10,20,30])
print('Row-wise broadcasting:\n', x + row_values)

add scalar :
 [[11 13 14]
 [15 16 17]]
Row-wise broadcasting:
 [[11 23 34]
 [15 26 37]]


## 8. Mathematical Functions

In [63]:
x = np.array([1,4,9,16], dtype=float)
print("square root",np.sqrt(x))
print("exponent",np.exp(x))
print("log",np.log(x))
print('abs:', np.abs(np.array([-5,2,-8])))

square root [1. 2. 3. 4.]
exponent [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
log [0.         1.38629436 2.19722458 2.77258872]
abs: [5 2 8]


## 9. Statistics


In [68]:
x = np.array([10,20,30,40,50])
print('Sum:', np.sum(x))

print("mean",np.mean(x))
print("Median",np.median(x))
print("satndard deviation",np.std(x))
print("min",np.min(x))
print("max",np.max(x))
print("Variance",np.var(x))
print("25th percentile",np.percentile(x,25))
print("75th percentile",np.percentile(x,75))

Sum: 150
mean 30.0
Median 30.0
satndard deviation 14.142135623730951
min 10
max 50
Variance 200.0
25th percentile 20.0
75th percentile 40.0


## 12. Normalization and Standardization

Min-Max: `(x - min) / (max - min)`

Z-score: `(x - mean) / std`

In [70]:
x = np.array([10,20,30,40,50], dtype=float)
minmax=(x-np.min(x)/np.max(x)-np.min(x))
z=(x-np.mean(x))/np.std(x)
print("Minmax :",minmax)
print("z score : ",z)
print("new mean ",np.mean(z))
print("new std :",np.std(z))


Minmax : [-0.2  9.8 19.8 29.8 39.8]
z score :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
new mean  0.0
new std : 0.9999999999999999
